#!/bin/sh

#[[ $(pactl get-source-mute @DEFAULT_SOURCE@) == 'Mute: no' ]] && echo '[U]' > /tmp/.mic-pipe || echo '[M]' > /tmp/.mic-pipe &
[[ $(pactl get-source-mute @DEFAULT_SOURCE@) == 'Mute: no' ]] && echo '[U]' || echo '[M]'
