#!/bin/sh

#case $1 in
#    "+") pamixer -i 5;;
#    "-") pamixer -d 5;;
#    "t") pamixer -t ;;
#esac

pref=$([[ $(pamixer --get-mute) == "true" ]] && echo "M" || echo "V")
perc=$(pamixer --get-volume)

if [[ $perc == "100" ]]; then
    perc="MX"
elif [[ $perc -lt "10" ]]; then
    perc="0$perc"
fi

#echo "$pref [$perc]" > /tmp/.volume-pipe
echo "$pref [$perc]"
